# Generated by Django 5.2.12 on 2026-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(max_length=30),
        ),
    ]
