# Generated by Django 5.2.12 on 2026-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModelForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=50)),
                ('student_branch', models.CharField(max_length=50)),
                ('student_email', models.EmailField(max_length=20)),
                ('student_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
