# Generated by Django 5.2.12 on 2026-03-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentModelForm',
            new_name='Student',
        ),
    ]
