# Generated by Django 5.2.12 on 2026-03-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModelForm',
        ),
    ]
